# Test GROUP BY with all the choices of GroupCondition

PREFIX ex: <http://example.org/func#>

SELECT *
WHERE {
  ?s ?p ?o .
}

# 1. BuiltInCall
# 2. FunctionCall
# 3. Expression AS VarName
# 4. Var
GROUP BY
  STR(?o)
  ex:foo(?o)
  ( ?o AS q )
  ?o

ORDER BY ?o
