.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" roqet.1 - Rasqal RDF query test program
.\"
.\" $Id$
.\"
.\" Copyright (C) 2004 David Beckett - http://purl.org/net/dajobe/
.\" Institute for Learning and Research Technology - http://www.ilrt.bris.ac.uk/
.\" University of Bristol - http://www.bristol.ac.uk/
.\"
.TH roqet 1 "2004-10-16"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
roqet \- Rasqal RDF parser utility
.SH SYNOPSIS
.B roqet
.RB [ OPTIONS ]
.IR "<query-URI>"
.IR "[base-URI]"
.SH EXAMPLE
.nf
.B roqet example.rdql
.br
.B roqet -q x.rdql http://example.org/base/
.br
.B roqet -i sparql http://example.org/query.sparql
.br
.SH DESCRIPTION
The
.B roqet
utility allows the querying of RDF content using the
.B Rasqal
RDF query library, emitting the results as variable bindings
(at present).  The query is read from \fIquery-URI\fR and
the optional \fIbase-URI\fR is used as the base URI if present.
.SH OPTIONS
roqet uses the usual GNU command line syntax, with long
options starting with two dashes (`-') if supported by the
getopt_long function.  Otherwise the short options are only available.
.TP
.B \-h, \-\-help
Show a summary of the options.
.TP
.B \-i, \-\-input LANGUAGE
Set the input query
.I LANGUAGE
to one of 'rdql' (RDF Data Query Language, default) and
'sparql' (SPARQL Query Language for RDF).   The list of
supported languages is given in the help summary given by \-h.
.TP
.B \-o, \-\-output FORMAT
Set the query result output
.I FORMAT
to 'simple' (default) or 'xml' (an experimental XML format)
.TP
.B \-c, \-\-count
Only count the triples and produce no other output.
.TP
.B \-d, \-\-dump-query
Print a debugging dump of the constructed query.
.TP
.B \-q, \-\-quiet
No extra information messages.
.TP
.B \-s, \-\-source URI
Query against RDF data at source
.I URI
by adding it to the list of query data source URIs.
.I FORMAT
to 'simple' (default) or 'xml' (an experimental XML format)
.TP
.B \-v, \-\-version
Print the rasqal library version and exit.
.SH "CONFORMING TO"
\fIRDQL RDF Data Query Language\fR,
HP Labs,
.UR http://www.hpl.hp.com/semweb/rdql.htm
http://www.hpl.hp.com/semweb/rdql.htm
.UE
\fISPARQL Query Language for RDF\fR,
Edited by Eric Prud'hommeaux and Andy Seaborne,
W3C Working Draft, 12 October 2004.  Work in progress.
.UR http://www.w3.org/TR/2004/WD-rdf-sparql-query-20041012/
http://www.w3.org/TR/2004/WD-rdf-sparql-query-20041012/
.UE

.SH SEE ALSO
.BR librasqal(3), rasqal-config(1)
.SH CHANGES
.br
.SH AUTHOR
Dave Beckett - 
.UR http://purl.org/net/dajobe/
http://purl.org/net/dajobe/
.UE
.br
.UR
Institute for Learning and Research Technology (ILRT)
http://www.ilrt.bristol.ac.uk/
.UE
.br
.UR
University of Bristol
http://www.bristol.ac.uk/
.UE

