# Test GROUP_CONCAT() with default separator
PREFIX ex: <http://example.org/>
SELECT ?state (GROUP_CONCAT(?name) AS ?residents) 
WHERE
{
  ?person ex:name ?name .
  ?person ex:livesIn ?state
}
GROUP BY ?state
