# http://lists.w3.org/Archives/Public/public-rdf-dawg/2010JanMar/0569.html

WITH <http://graph.example.org/g1>
INSERT DATA {
   <http://example.org/x1> <http://example.org/p1> 123

   GRAPH <http://graph.example.org/g2> {
     <http://example.org/x2> <<http://example.org/p2> 456 .
   }

   GRAPH <http://graph.example.org/g3> {
     <http://example.org/x1> <<http://example.org/p1> 123
   }
}
