# http://www.w3.org/2009/sparql/docs/update-1.1/Overview.xml#t411
# Editor's Draft 18 December 2009

PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA
{ <http://example/book3> dc:title    "A new book" ;
                         dc:creator  "A.N.Other" .
}
