# http://www.w3.org/TR/2008/REC-rdf-sparql-query-20080115/#convertGraphPattern
#
# Example: group consisting of a basic graph pattern, a filter and an optional graph pattern:
#
PREFIX : <http://example.org#>
SELECT * WHERE
{ ?s :p1 ?v1 FILTER (?v1 < 3 ) OPTIONAL {?s :p2 ?v2} }
